//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationAlunos.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Aluno", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Aluno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        private double NotaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Nota {
            get {
                return this.NotaField;
            }
            set {
                if ((this.NotaField.Equals(value) != true)) {
                    this.NotaField = value;
                    this.RaisePropertyChanged("Nota");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServicoAlunoSoap")]
    public interface ServicoAlunoSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebApplicationAlunos.ServiceReference1.HelloWorldResponse HelloWorld(WebApplicationAlunos.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplicationAlunos.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WebApplicationAlunos.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name CarregaAlunoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CarregaAluno", ReplyAction="*")]
        WebApplicationAlunos.ServiceReference1.CarregaAlunoResponse CarregaAluno(WebApplicationAlunos.ServiceReference1.CarregaAlunoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CarregaAluno", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplicationAlunos.ServiceReference1.CarregaAlunoResponse> CarregaAlunoAsync(WebApplicationAlunos.ServiceReference1.CarregaAlunoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationAlunos.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebApplicationAlunos.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationAlunos.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebApplicationAlunos.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CarregaAlunoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CarregaAluno", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationAlunos.ServiceReference1.CarregaAlunoRequestBody Body;
        
        public CarregaAlunoRequest() {
        }
        
        public CarregaAlunoRequest(WebApplicationAlunos.ServiceReference1.CarregaAlunoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CarregaAlunoRequestBody {
        
        public CarregaAlunoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CarregaAlunoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CarregaAlunoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplicationAlunos.ServiceReference1.CarregaAlunoResponseBody Body;
        
        public CarregaAlunoResponse() {
        }
        
        public CarregaAlunoResponse(WebApplicationAlunos.ServiceReference1.CarregaAlunoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CarregaAlunoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplicationAlunos.ServiceReference1.Aluno[] CarregaAlunoResult;
        
        public CarregaAlunoResponseBody() {
        }
        
        public CarregaAlunoResponseBody(WebApplicationAlunos.ServiceReference1.Aluno[] CarregaAlunoResult) {
            this.CarregaAlunoResult = CarregaAlunoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicoAlunoSoapChannel : WebApplicationAlunos.ServiceReference1.ServicoAlunoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoAlunoSoapClient : System.ServiceModel.ClientBase<WebApplicationAlunos.ServiceReference1.ServicoAlunoSoap>, WebApplicationAlunos.ServiceReference1.ServicoAlunoSoap {
        
        public ServicoAlunoSoapClient() {
        }
        
        public ServicoAlunoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoAlunoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoAlunoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoAlunoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplicationAlunos.ServiceReference1.HelloWorldResponse WebApplicationAlunos.ServiceReference1.ServicoAlunoSoap.HelloWorld(WebApplicationAlunos.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebApplicationAlunos.ServiceReference1.HelloWorldRequest inValue = new WebApplicationAlunos.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebApplicationAlunos.ServiceReference1.HelloWorldRequestBody();
            WebApplicationAlunos.ServiceReference1.HelloWorldResponse retVal = ((WebApplicationAlunos.ServiceReference1.ServicoAlunoSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplicationAlunos.ServiceReference1.HelloWorldResponse> WebApplicationAlunos.ServiceReference1.ServicoAlunoSoap.HelloWorldAsync(WebApplicationAlunos.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplicationAlunos.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WebApplicationAlunos.ServiceReference1.HelloWorldRequest inValue = new WebApplicationAlunos.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebApplicationAlunos.ServiceReference1.HelloWorldRequestBody();
            return ((WebApplicationAlunos.ServiceReference1.ServicoAlunoSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplicationAlunos.ServiceReference1.CarregaAlunoResponse WebApplicationAlunos.ServiceReference1.ServicoAlunoSoap.CarregaAluno(WebApplicationAlunos.ServiceReference1.CarregaAlunoRequest request) {
            return base.Channel.CarregaAluno(request);
        }
        
        public WebApplicationAlunos.ServiceReference1.Aluno[] CarregaAluno() {
            WebApplicationAlunos.ServiceReference1.CarregaAlunoRequest inValue = new WebApplicationAlunos.ServiceReference1.CarregaAlunoRequest();
            inValue.Body = new WebApplicationAlunos.ServiceReference1.CarregaAlunoRequestBody();
            WebApplicationAlunos.ServiceReference1.CarregaAlunoResponse retVal = ((WebApplicationAlunos.ServiceReference1.ServicoAlunoSoap)(this)).CarregaAluno(inValue);
            return retVal.Body.CarregaAlunoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplicationAlunos.ServiceReference1.CarregaAlunoResponse> WebApplicationAlunos.ServiceReference1.ServicoAlunoSoap.CarregaAlunoAsync(WebApplicationAlunos.ServiceReference1.CarregaAlunoRequest request) {
            return base.Channel.CarregaAlunoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplicationAlunos.ServiceReference1.CarregaAlunoResponse> CarregaAlunoAsync() {
            WebApplicationAlunos.ServiceReference1.CarregaAlunoRequest inValue = new WebApplicationAlunos.ServiceReference1.CarregaAlunoRequest();
            inValue.Body = new WebApplicationAlunos.ServiceReference1.CarregaAlunoRequestBody();
            return ((WebApplicationAlunos.ServiceReference1.ServicoAlunoSoap)(this)).CarregaAlunoAsync(inValue);
        }
    }
}
