//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationFuncionario.FuncionarioServico {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Funcionario", Namespace="http://schemas.datacontract.org/2004/07/WCF_Funcionario")]
    [System.SerializableAttribute()]
    public partial class Funcionario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataCadastroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SalarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataCadastro {
            get {
                return this.DataCadastroField;
            }
            set {
                if ((this.DataCadastroField.Equals(value) != true)) {
                    this.DataCadastroField = value;
                    this.RaisePropertyChanged("DataCadastro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Salario {
            get {
                return this.SalarioField;
            }
            set {
                if ((this.SalarioField.Equals(value) != true)) {
                    this.SalarioField = value;
                    this.RaisePropertyChanged("Salario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FuncionarioServico.IFuncionario")]
    public interface IFuncionario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuncionario/ListarFuncionario", ReplyAction="http://tempuri.org/IFuncionario/ListarFuncionarioResponse")]
        WebApplicationFuncionario.FuncionarioServico.Funcionario[] ListarFuncionario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuncionario/ListarFuncionario", ReplyAction="http://tempuri.org/IFuncionario/ListarFuncionarioResponse")]
        System.Threading.Tasks.Task<WebApplicationFuncionario.FuncionarioServico.Funcionario[]> ListarFuncionarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuncionario/SelecionarFuncionario", ReplyAction="http://tempuri.org/IFuncionario/SelecionarFuncionarioResponse")]
        WebApplicationFuncionario.FuncionarioServico.Funcionario SelecionarFuncionario(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFuncionario/SelecionarFuncionario", ReplyAction="http://tempuri.org/IFuncionario/SelecionarFuncionarioResponse")]
        System.Threading.Tasks.Task<WebApplicationFuncionario.FuncionarioServico.Funcionario> SelecionarFuncionarioAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFuncionarioChannel : WebApplicationFuncionario.FuncionarioServico.IFuncionario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FuncionarioClient : System.ServiceModel.ClientBase<WebApplicationFuncionario.FuncionarioServico.IFuncionario>, WebApplicationFuncionario.FuncionarioServico.IFuncionario {
        
        public FuncionarioClient() {
        }
        
        public FuncionarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FuncionarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FuncionarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FuncionarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplicationFuncionario.FuncionarioServico.Funcionario[] ListarFuncionario() {
            return base.Channel.ListarFuncionario();
        }
        
        public System.Threading.Tasks.Task<WebApplicationFuncionario.FuncionarioServico.Funcionario[]> ListarFuncionarioAsync() {
            return base.Channel.ListarFuncionarioAsync();
        }
        
        public WebApplicationFuncionario.FuncionarioServico.Funcionario SelecionarFuncionario(int id) {
            return base.Channel.SelecionarFuncionario(id);
        }
        
        public System.Threading.Tasks.Task<WebApplicationFuncionario.FuncionarioServico.Funcionario> SelecionarFuncionarioAsync(int id) {
            return base.Channel.SelecionarFuncionarioAsync(id);
        }
    }
}
